// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_jobs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkIdempotency = `-- name: CheckIdempotency :one
SELECT id FROM email_jobs WHERE idempotency_key = $1 LIMIT 1
`

func (q *Queries) CheckIdempotency(ctx context.Context, idempotencyKey pgtype.Text) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, checkIdempotency, idempotencyKey)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const countJobs = `-- name: CountJobs :one
SELECT COUNT(*) FROM email_jobs
WHERE ($1::text IS NULL OR status = $1)
`

func (q *Queries) CountJobs(ctx context.Context, dollar_1 string) (int64, error) {
	row := q.db.QueryRow(ctx, countJobs, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const dequeueJob = `-- name: DequeueJob :one
UPDATE email_jobs
SET status = 'processing', locked_at = now(), updated_at = now()
WHERE id = (
    SELECT id FROM email_jobs
    WHERE status = 'pending'
      AND (next_retry_at IS NULL OR next_retry_at <= now())
    ORDER BY priority DESC, created_at ASC
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, idempotency_key, from_email, to_email, subject, body, status, priority, attempt_count, max_attempts, next_retry_at, locked_at, last_error, created_at, updated_at, sent_at
`

func (q *Queries) DequeueJob(ctx context.Context) (EmailJob, error) {
	row := q.db.QueryRow(ctx, dequeueJob)
	var i EmailJob
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.FromEmail,
		&i.ToEmail,
		&i.Subject,
		&i.Body,
		&i.Status,
		&i.Priority,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.NextRetryAt,
		&i.LockedAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SentAt,
	)
	return i, err
}

const enqueueJob = `-- name: EnqueueJob :one
INSERT INTO email_jobs (idempotency_key, from_email, to_email, subject, body, priority, max_attempts)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type EnqueueJobParams struct {
	IdempotencyKey pgtype.Text `json:"idempotency_key"`
	FromEmail      string      `json:"from_email"`
	ToEmail        string      `json:"to_email"`
	Subject        string      `json:"subject"`
	Body           string      `json:"body"`
	Priority       int16       `json:"priority"`
	MaxAttempts    int32       `json:"max_attempts"`
}

func (q *Queries) EnqueueJob(ctx context.Context, arg EnqueueJobParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, enqueueJob,
		arg.IdempotencyKey,
		arg.FromEmail,
		arg.ToEmail,
		arg.Subject,
		arg.Body,
		arg.Priority,
		arg.MaxAttempts,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const findStuckJobs = `-- name: FindStuckJobs :many
SELECT id, idempotency_key, from_email, to_email, subject, body, status, priority, attempt_count, max_attempts, next_retry_at, locked_at, last_error, created_at, updated_at, sent_at FROM email_jobs
WHERE status = 'processing'
  AND locked_at < now() - INTERVAL '10 minutes'
ORDER BY locked_at ASC
LIMIT $1
`

func (q *Queries) FindStuckJobs(ctx context.Context, limit int32) ([]EmailJob, error) {
	rows, err := q.db.Query(ctx, findStuckJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmailJob
	for rows.Next() {
		var i EmailJob
		if err := rows.Scan(
			&i.ID,
			&i.IdempotencyKey,
			&i.FromEmail,
			&i.ToEmail,
			&i.Subject,
			&i.Body,
			&i.Status,
			&i.Priority,
			&i.AttemptCount,
			&i.MaxAttempts,
			&i.NextRetryAt,
			&i.LockedAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJob = `-- name: GetJob :one
SELECT id, idempotency_key, from_email, to_email, subject, body, status, priority, attempt_count, max_attempts, next_retry_at, locked_at, last_error, created_at, updated_at, sent_at FROM email_jobs WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, id pgtype.UUID) (EmailJob, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i EmailJob
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.FromEmail,
		&i.ToEmail,
		&i.Subject,
		&i.Body,
		&i.Status,
		&i.Priority,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.NextRetryAt,
		&i.LockedAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SentAt,
	)
	return i, err
}

const listJobs = `-- name: ListJobs :many
SELECT id, idempotency_key, from_email, to_email, subject, body, status, priority, attempt_count, max_attempts, next_retry_at, locked_at, last_error, created_at, updated_at, sent_at FROM email_jobs
WHERE ($1::text IS NULL OR status = $1)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListJobsParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]EmailJob, error) {
	rows, err := q.db.Query(ctx, listJobs, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmailJob
	for rows.Next() {
		var i EmailJob
		if err := rows.Scan(
			&i.ID,
			&i.IdempotencyKey,
			&i.FromEmail,
			&i.ToEmail,
			&i.Subject,
			&i.Body,
			&i.Status,
			&i.Priority,
			&i.AttemptCount,
			&i.MaxAttempts,
			&i.NextRetryAt,
			&i.LockedAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDeadLetter = `-- name: MarkDeadLetter :exec
UPDATE email_jobs
SET status = 'dead_letter', updated_at = now()
WHERE id = $1
`

func (q *Queries) MarkDeadLetter(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markDeadLetter, id)
	return err
}

const markFailed = `-- name: MarkFailed :exec
UPDATE email_jobs
SET status = 'failed',
    attempt_count = attempt_count + 1,
    last_error = $2,
    next_retry_at = $3,
    locked_at = NULL,
    updated_at = now()
WHERE id = $1
`

type MarkFailedParams struct {
	ID          pgtype.UUID        `json:"id"`
	LastError   pgtype.Text        `json:"last_error"`
	NextRetryAt pgtype.Timestamptz `json:"next_retry_at"`
}

func (q *Queries) MarkFailed(ctx context.Context, arg MarkFailedParams) error {
	_, err := q.db.Exec(ctx, markFailed, arg.ID, arg.LastError, arg.NextRetryAt)
	return err
}

const markSent = `-- name: MarkSent :exec
UPDATE email_jobs
SET status = 'sent', sent_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) MarkSent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markSent, id)
	return err
}
