// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_job_attempts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAttemptsForJob = `-- name: GetAttemptsForJob :many
SELECT id, job_id, attempt_number, status, error_message, smtp_response_code, attempted_at FROM email_job_attempts
WHERE job_id = $1
ORDER BY attempt_number ASC
`

func (q *Queries) GetAttemptsForJob(ctx context.Context, jobID pgtype.UUID) ([]EmailJobAttempt, error) {
	rows, err := q.db.Query(ctx, getAttemptsForJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmailJobAttempt
	for rows.Next() {
		var i EmailJobAttempt
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.AttemptNumber,
			&i.Status,
			&i.ErrorMessage,
			&i.SmtpResponseCode,
			&i.AttemptedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordAttempt = `-- name: RecordAttempt :one
INSERT INTO email_job_attempts (job_id, attempt_number, status, error_message, smtp_response_code)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type RecordAttemptParams struct {
	JobID            pgtype.UUID `json:"job_id"`
	AttemptNumber    int32       `json:"attempt_number"`
	Status           string      `json:"status"`
	ErrorMessage     pgtype.Text `json:"error_message"`
	SmtpResponseCode pgtype.Text `json:"smtp_response_code"`
}

func (q *Queries) RecordAttempt(ctx context.Context, arg RecordAttemptParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, recordAttempt,
		arg.JobID,
		arg.AttemptNumber,
		arg.Status,
		arg.ErrorMessage,
		arg.SmtpResponseCode,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
