// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type EmailJob struct {
	ID             pgtype.UUID        `json:"id"`
	IdempotencyKey pgtype.Text        `json:"idempotency_key"`
	FromEmail      string             `json:"from_email"`
	ToEmail        string             `json:"to_email"`
	Subject        string             `json:"subject"`
	Body           string             `json:"body"`
	Status         string             `json:"status"`
	Priority       int16              `json:"priority"`
	AttemptCount   int32              `json:"attempt_count"`
	MaxAttempts    int32              `json:"max_attempts"`
	NextRetryAt    pgtype.Timestamptz `json:"next_retry_at"`
	LockedAt       pgtype.Timestamptz `json:"locked_at"`
	LastError      pgtype.Text        `json:"last_error"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	SentAt         pgtype.Timestamptz `json:"sent_at"`
}

type EmailJobAttempt struct {
	ID               pgtype.UUID        `json:"id"`
	JobID            pgtype.UUID        `json:"job_id"`
	AttemptNumber    int32              `json:"attempt_number"`
	Status           string             `json:"status"`
	ErrorMessage     pgtype.Text        `json:"error_message"`
	SmtpResponseCode pgtype.Text        `json:"smtp_response_code"`
	AttemptedAt      pgtype.Timestamptz `json:"attempted_at"`
}
